on: [pull_request]

jobs:
  check_branch_name_job:
    runs-on: ubuntu-latest
    name: A job to check branch name
    steps:
      - name: Run check on branch name
        uses: sharma-sandy/check-branch-name-action@main
        with:
          token: ${{github.token}}
